updates to install1 and lsenv

diff --git a/usr/local/sbin/install1 b/usr/local/sbin/install1
--- a/usr/local/sbin/install1
+++ b/usr/local/sbin/install1
@@ -3,65 +3,111 @@
 # install1 - first install script to configure a newly flashed Ubuntu Desktop 22.04
 #            this will prepare it to become an OVOS/Mycroft platform
 #
-echo "installing co-req packages ..."
-sudo apt-get install -y vim git mlocate net-tools python3 python3-pip python3-rpi.gpio python3.10-venv mpc mpd
+#+--------------------------------------------------------------------------+
+function runCmd
+# run a command, report time spent and exit if it failes
+#+--------------------------------------------------------------------------+
+ {
+  : SOURCE: ${BASH_SOURCE}
+  : STACK:  ${FUNCNAME[@]}
 
-echo "setting vim to default editor ..."
-ln -s /usr/bin/vim.basic /etc/alternatives/vim  
+  cmd="$@"                                 # get all args
+  eval time $cmd                           # run the command and report time spent
+  rc=$?
+  if [ "$rc" != 0 ]; then                  # it failed
+    echo "ERROR: $cmd returned $rc"
+    exit 1
+  fi
+  echo ""
+ }                                         # runCmd()
 
-echo "setting vim to better colors ..."
-grep "colorscheme desert" /etc/vim/vimrc >/dev/null 2>&1
-if [ $? != 0 ]; then 
-  sudo sed -i -e 's/syntax on/syntax on\n  colorscheme desert/g' /etc/vim/vimrc
-fi  
+#+--------------------------------------------------------------------------+
+function installCoreqs
+# Do the work to install and configure everything to run Mycroft driven by ovos-core
+#+--------------------------------------------------------------------------+
+ {
+  : SOURCE: ${BASH_SOURCE}
+  : STACK:  ${FUNCNAME[@]}
 
-echo "adding groups to users pi and mpd ..."
-sudo usermod -a -G video,pulse,pulse-access,dialout,kmem pi
-sudo usermod -a -G pulse-access,pi mpd
+  echo "installing co-req packages ..."
+  runCmd sudo apt-get install -y vim git mlocate net-tools python3 python3-pip python3-rpi.gpio python3.10-venv mpc mpd
+  
+  echo "setting vim to default editor ..."
+  runCmd ln -s /usr/bin/vim.basic /etc/alternatives/vim  
+  
+  echo "setting vim to better colors ..."
+  grep "colorscheme desert" /etc/vim/vimrc >/dev/null 2>&1
+  if [ $? != 0 ]; then                     # it has not already been added
+    sudo sed -i -e 's/syntax on/syntax on\n  colorscheme desert/g' /etc/vim/vimrc
+  fi  
+  
+  echo "adding groups to users pi and mpd ..."
+  runCmd sudo usermod -a -G video,pulse,pulse-access,dialout,kmem pi
+  runCmd sudo usermod -a -G pulse-access,pi mpd
+  
+  # copy a .bash_profile from mycroft-tools
+  if [ -f ~/mycroft-tools/bash_profile ]; then
+    echo "copying .bash_profile ..."
+    runCmd cp ~/mycroft-tools/bash_profile ~/.bash_profile
+  fi  
+  
+  # turn default and vc4 audio off, don't disable monitor overscan
+  echo "customizing boot parameters ..."
+  cd /boot/firmware
+  if [ ! -f config.txt.orig ]; then
+    runCmd sudo cp config.txt config.txt.orig
+  fi  
+  sudo sed -i -e 's/dtparam=audio=on/dtparam=audio=off\ndtparam=spi=off/g' \
+              -e 's/^disable_overscan/# disable_overscan/g' \
+              -e 's/^dtoverlay=vc4-kms-v3/# dtoverlay=vc4-kms-v3/g' config.txt
+  
+  # vim - please just give me a newline
+  echo "removing annoying autoindent from vim ..."
+  cd /usr/share/vim/vim82
+  if [ -f indent.vim ]; then
+    runCmd sudo mv indent.vim indent.vim.dontuse
+  fi  
+  if [ ! -d ~/.vim/indent ]; then
+    runCmd mkdir -p ~/.vim/indent
+  fi  
+  if [ ! -f ~/.vim/indent/html.vim ]; then
+    echo "let b:did_indent = 1" > ~/.vim/indent/html.vim
+  fi  
+  
+  # rsyslog can send a flood of kernel messages
+  if [ -f /etc/rsyslog.conf ]; then 
+    echo "preventing rsyslogd from making message storms ..."
+    runCmd sudo cp /etc/rsyslogd.conf /etc/rsyslog.conf.orig
+    sudo sed -i 's/module(load="imklog"/# module(load="imklog"/g' /etc/rsyslog.conf
+  else
+    echo "WARNING: /etc/rsyslog.conf not found"
+  fi
+  
+  # to lengthen the life of the SD card write logs to tmpfs file systems
+  if [ -f ~/mycroft-tools/tmpfs.service ]; then
+    echo "copying tmpfs.service ..."
+    runCmd sudo cp ~/mycroft-tools/tmpfs.service /etc/systemd/system
+    runCmd sudo systemctl enable tmpfs
+  fi
+  
+  # start pulseaudio as a service
+  serviceFile=/etc/systemd/system/pulseaudio.service
+  if [ -f $serviceFile ]; then               # do not overwrite
+    echo "WARNING: pulse systemd file $serviceFile already exists"
+  else                                       # copy service file
+    runCmd sudo cp ~/mycroft-tools/pulseaudio.service /etc/systemd/system
+    runCmd sudo systemctl enable pulseaudio
+  fi 
+  
+  # prevent pulseaudio from starting multiple times
+  runCmd sudo cp /home/pi/mycroft-tools/pulseaudio.service.old /usr/lib/systemd/user
+  runCmd sudo cp /home/pi/mycroft-tools/pulseaudio.socket /usr/lib/systemd/user
+ }                                         # installCoreqs()
 
-# copy a .bash_profile from mycroft-tools
-if [ -f ~/mycroft-tools/bash_profile ]; then
-  echo "copying .bash_profile ..."
-  cp  ~/mycroft-tools/bash_profile ~/.bash_profile
-fi  
-
-# turn default and vc4 audio off, don't disable monitor overscan
-echo "customizing boot parameters ..."
-cd /boot/firmware
-if [ ! -f config.txt.orig ]; then
-  sudo cp config.txt config.txt.orig
-fi  
-sudo sed -i -e 's/dtparam=audio=on/dtparam=audio=off\ndtparam=spi=off/g' \
-            -e 's/^disable_overscan/# disable_overscan/g' \
-            -e 's/^dtoverlay=vc4-kms-v3/# dtoverlay=vc4-kms-v3/g' config.txt
-
-# vim - please just give me a newline
-echo "removing annoying autoindent from vim ..."
-cd /usr/share/vim/vim82
-if [ -f indent.vim ]; then
-  sudo mv indent.vim indent.vim.dontuse
-fi  
-if [ ! -d ~/.vim/indent ]; then
-  mkdir -p ~/.vim/indent
-fi  
-if [ ! -f ~/.vim/indent/html.vim ]; then
-  echo "let b:did_indent = 1" > ~/.vim/indent/html.vim
-fi  
-
-# rsyslog can send a flood of kernel messages
-if [ -f /etc/rsyslog.conf ]; then 
-  echo "preventing rsyslogd from making message storms ..."
-  sudo cp /etc/rsyslogd.conf /etc/rsyslog.conf.orig
-  sudo sed -i 's/module(load="imklog"/# module(load="imklog"/g' /etc/rsyslog.conf
-else
-  echo "WARNING: /etc/rsyslog.conf not found"
-fi
-
-# to lengthen the life of the SD card write logs to tmpfs file systems
-if [ -f ~/mycroft-tools/tmpfs.service ]; then
-  echo "copying tmpfs.service ..."
-  sudo cp ~/mycroft-tools/tmpfs.service /etc/systemd/system
-  sudo systemctl enable tmpfs
-fi
-
+# main()
+SECONDS=0                                  # reset stopwatch
+installCoreqs                              # do the work
+let min=$SECONDS/60
+let sec=$SECONDS%60
+echo "successfully installed co-reqs for Mycroft in $min:$sec"
 
diff --git a/usr/local/sbin/lsenv b/usr/local/sbin/lsenv
--- a/usr/local/sbin/lsenv
+++ b/usr/local/sbin/lsenv
@@ -94,7 +94,6 @@ function getCPU()
   : SOURCE: ${BASH_SOURCE}
   : STACK:  ${FUNCNAME[@]}
 
-  echo -n "CPU usage:" 
   local cpu_total=0
   for i in 1 2 3 4; do
     # Get the first line with aggregate of all CPUs 
@@ -122,7 +121,50 @@ function getCPU()
     sleep 1 
   done
   let cpu_usage=$cpu_total/3               # calculate average
-  echo "   $cpu_usage%"                    # show it
+  printf "%15s : %s\n" "CPU usage" "$cpu_usage"
+ }                                         # getCPU()
+
+#+--------------------------------------------------------------------------+
+function listTemp()
+# lstemp - show the temperature of the Raspberry Pi based on
+#          the file /sys/class/thermal/thermal_zone0/temp
+#+--------------------------------------------------------------------------+
+ {
+  : SOURCE: ${BASH_SOURCE}
+  : STACK:  ${FUNCNAME[@]}
+
+  local tempFile="/sys/class/thermal/thermal_zone0/temp"
+  if [ ! -f $tempFile ]; then              # file not found
+    echo "ERROR: did not find $tempFile"
+    exit 1
+  fi
+  local theTemp=`cat /sys/class/thermal/thermal_zone0/temp` # in thousdandths of degrees celcius
+  let theTemp=$theTemp/1000                # convert to degrees Celcius
+  let tempF=$theTemp*9/5+32                # convert to degrees Farenheit
+  echo "CPU temperature : ${theTemp}C / ${tempF}F"
+ }                                         # listTemp()
+
+#+--------------------------------------------------------------------------+
+function tmpfsUsage()
+# Is the directory passed in using a tmpfs? 
+#+--------------------------------------------------------------------------+
+ {
+  : SOURCE: ${BASH_SOURCE}
+  : STACK:  ${FUNCNAME[@]}
+
+  local theDir=$1
+  local answer
+
+  mount | grep $theDir | grep tmpfs >/dev/null 2>&1
+  if [ $? = 0 ]; then                      # directory is using a tmpfs       
+    answer=yes
+  else
+    answer=no
+  fi
+  if [ "$theDir" = ".local/state/mycroft" ]; then # make more readable
+    theDir="Mycroft logs"
+  fi
+  printf "%15s : %s\n" "$theDir" "$answer"
  }                                         # getCPU()
 
 #+--------------------------------------------------------------------------+
@@ -141,18 +183,29 @@ function doList()
   listService pulseaudio 
   listService pipewire 
   
-  # also consicely list IP address, temperature, CPU and memory usage
+  # also list many other settings and status 
   local IPaddr=`hostname -I | awk '{print $1}'` # get the IP address
-  echo "IP address:  $IPaddr"
-  /usr/local/sbin/lstemp | sed 's/^Raspberry Pi //g' # temp of the RasPi
+  printf "%15s : %s\n" "IP address" "$IPaddr"
 
-  # get memory usage
-  echo "Memory usage:"
-  free -h | sed 's/^/  /g'
+  # RasPi temperature
+  listTemp
+
+  # root file system usage
+  local rootUsed=`df -h / | tail -1 | awk '{print $5}'`
+  printf "%15s : %s\n" "Root fs usage" "$rootUsed"
 
   # get CPU usage
   getCPU  
-  echo $dashes 
+
+  # get memory usage
+  echo "Memory usage    :"
+  free -h | sed 's/^/  /g'                 # add two leading spaces
+
+  # are log directories using tmpfs? 
+  echo "tmpfs filesystem?"
+  tmpfsUsage ".local/state/mycroft"
+  tmpfsUsage /var/log 
+  echo
  }                                         # doList()
 
 #+--------------------------------------------------------------------------+
