all updates and additions for 5/23/22 version

diff --git a/usr/local/sbin/lstemp b/usr/local/sbin/lstemp
--- a/usr/local/sbin/lstemp
+++ b/usr/local/sbin/lstemp
@@ -1,14 +1,77 @@
 #!/bin/bash
 #
-# lstemp - show the temperature of the Raspberry Pi based on 
-#          the file /sys/class/thermal/thermal_zone0/temp
+# lstemp - show a summary of all tools/scripts in mycroft-tools 
 #
-tempFile="/sys/class/thermal/thermal_zone0/temp"
-if [ ! -f $tempFile ]; then                # file not found
-  echo "ERROR: did not find $tempFile"
-  exit 1
-fi  
-theTemp=`cat /sys/class/thermal/thermal_zone0/temp` # in thousdandths of degrees celcius
-let theTemp=$theTemp/1000                  # convert to degrees Celcius
-let tempF=$theTemp*9/5+32                  # convert to degrees Farenheit
-echo "Raspberry Pi temperature: ${theTemp}C / ${tempF}F"
+#+--------------------------------------------------------------------------+
+function usage()
+# Give help to the user
+#+--------------------------------------------------------------------------+
+ {
+  : SOURCE: ${BASH_SOURCE}
+  : STACK:  ${FUNCNAME[@]}
+
+  echo                                     # leave some room
+  echo "Name: lstemp - Show a summary of all tools/scripts in mycroft-tools" 
+  echo "Usage: lstemp [OPTIONS]"
+  echo ""
+  echo "OPTIONS:"
+  echo "  -h|--help         Give help (this screen)"
+  echo "  -x|--debug        Print commands and arguments as they are executed"
+  exit 51
+ }                                         # usage()
+
+#+--------------------------------------------------------------------------+
+function parseArgs()
+# Parse arguments
+# Args: All arguments passed into script
+#+--------------------------------------------------------------------------+
+ {
+  : SOURCE: ${BASH_SOURCE}
+  : STACK:  ${FUNCNAME[@]}
+
+  while [ -n "$1" ]                        # loop through args passed in
+  do
+    case "$1" in
+      -h|--help)
+        usage
+        ;;
+      -x|--debug)                          # turn trace on
+         set -vx
+         ;;
+      *)
+	echo "ERROR: Too many arguments: $1"
+	exit 4 
+        ;;
+    esac
+    shift
+  done
+ }                                         # parseArgs()
+
+#+--------------------------------------------------------------------------+
+function listTemp()
+# lstemp - show the temperature of the Raspberry Pi based on
+#          the file /sys/class/thermal/thermal_zone0/temp
+#+--------------------------------------------------------------------------+
+ {
+  : SOURCE: ${BASH_SOURCE}
+  : STACK:  ${FUNCNAME[@]}
+
+  local tempFile="/sys/class/thermal/thermal_zone0/temp"
+  if [ ! -f $tempFile ]; then              # file not found
+    echo "ERROR: did not find $tempFile"
+    exit 1
+  fi
+  local theTemp=`cat /sys/class/thermal/thermal_zone0/temp` # in thousdandths of degrees celcius
+  let theTemp=$theTemp/1000                # convert to degrees Celcius
+  let tempF=$theTemp*9/5+32                # convert to degrees Farenheit
+  echo "Raspberry Pi temperature: ${theTemp}C / ${tempF}F"
+ }                                         # listTemp()
+  
+#+--------------------------------------------------------------------------+
+# Global variables"
+outputType="short"                          # short or long listing 
+
+# main()
+parseArgs $@                                # parse arguments
+listTemp                                    # list temperature
+
diff --git a/usr/local/sbin/testplay b/usr/local/sbin/testplay
--- a/usr/local/sbin/testplay
+++ b/usr/local/sbin/testplay
@@ -1,5 +1,77 @@
 #!/bin/bash
 #
-# test playing a file that was recorded to
+# testplay - test recording with default microphone
 #
-aplay /tmp/test-mic.wav
+#+--------------------------------------------------------------------------+
+function usage()
+# Give help to the user
+#+--------------------------------------------------------------------------+
+ {
+  : SOURCE: ${BASH_SOURCE}
+  : STACK:  ${FUNCNAME[@]}
+
+  echo "testplay - test playing back recording from test file $testFile"
+  echo "Usage: testplay [OPTIONS]" 
+  echo ""
+  echo "OPTIONS:"
+  echo "  -h|--help         Give help (this screen)"
+  echo "  -v|--verbose      Increase verbosity" 
+  echo "  -x|--debug        Print commands and arguments as they are executed"
+  exit 51
+ }                                         # usage()
+
+#+--------------------------------------------------------------------------+
+function parseArgs()
+# Parse arguments
+# Args: All arguments passed into script
+#+--------------------------------------------------------------------------+
+ {
+  : SOURCE: ${BASH_SOURCE}
+  : STACK:  ${FUNCNAME[@]}
+
+  while [ -n "$1" ]                        # loop through args passed in
+  do
+    case "$1" in
+      -h|--help)
+        usage
+        ;;
+      -v|--verbose) 
+        verbose=2
+        ;;
+      -x|--debug)                          # turn trace on
+         set -vx
+         ;;
+      *)
+	echo "ERROR: Too many arguments: $1"
+	usage 
+        ;;
+    esac
+    shift
+  done
+ }                                         # parseArgs()
+
+#+--------------------------------------------------------------------------+
+function doTest()
+# test recording with default microphone
+#+--------------------------------------------------------------------------+
+ {
+  : SOURCE: ${BASH_SOURCE}
+  : STACK:  ${FUNCNAME[@]}
+
+  if [ ! -f $testFile ]; then 
+    echo "ERROR: did note find test recording in file $testFile"
+    echo "Did you run testrecord?"
+  else   
+    aplay $testFile 
+  fi	  
+ }                                         # doTest()
+
+#+--------------------------------------------------------------------------+
+# Global variables"
+testFile="/tmp/test-mic.wav"               # test recording file from testrecord
+verbose=1                                  # verbosity
+
+# main()
+parseArgs $@                               # parse arguments
+doTest                                     # perform the test 
+
diff --git a/usr/local/sbin/testrecord b/usr/local/sbin/testrecord
--- a/usr/local/sbin/testrecord
+++ b/usr/local/sbin/testrecord
@@ -1,32 +1,107 @@
 #!/bin/bash
 #
-# test recording with default microphone
+# testrecord - test recording with default microphone
 #
-# get microphone's sample rate, # of channels and format
-rate=`grep rate: /proc/asound/card*/pcm0c/sub0/hw_params | awk '{print $2}'` # there could be multiple mic's
-if [ ${#rate} = 0 ]; then                  # no mic found
-  echo "ERROR: no microphone found with command grep rate: /proc/asound/card*/pcm0c/sub0/hw_params"
-  exit 4                                   # cannot perform operation
-fi
-channels=`grep channels: /proc/asound/card*/pcm0c/sub0/hw_params | awk '{print $2}'`
-if [ ${#channels} = 0 ]; then              # number of channels not found
-  echo "WARNING: did not find number of channels - assuming 1"
-  channels=1                               # assume 1 channel
-fi
-format=`grep ^format: /proc/asound/card*/pcm0c/sub0/hw_params | awk '{print $2}'`
-if [ ${#format} = 0 ]; then                # format not found
-  echo "WARNING: did not find number of channels - ignoring" # leave empty
-else
-  format="-f $format"                      # add -f flag
-fi
+#+--------------------------------------------------------------------------+
+function usage()
+# Give help to the user
+#+--------------------------------------------------------------------------+
+ {
+  : SOURCE: ${BASH_SOURCE}
+  : STACK:  ${FUNCNAME[@]}
 
-# put the arecord command together and run it
-cmd="arecord $format -c $channels -d 5 -r $rate /tmp/test-mic.wav"
-echo "Testing your microphone for 5 seconds - SAY SOMETHING!"
-echo "INFO: running command: $cmd"
-$cmd                                       # run the command
-rc=$?
-if [ "$rc" != 0 ]; then                    # something didn't work
-  echo "ERROR: command $cmd failed with $rc"
-  exit $rc                                 # not successful
-fi
+  echo "testrecord - test recording with default microphone"
+  echo "Usage: testrecord [OPTIONS]" 
+  echo ""
+  echo "OPTIONS:"
+  echo "  -h|--help         Give help (this screen)"
+  echo "  -v|--verbose      Increase verbosity" 
+  echo "  -x|--debug        Print commands and arguments as they are executed"
+  exit 51
+ }                                         # usage()
+
+#+--------------------------------------------------------------------------+
+function parseArgs()
+# Parse arguments
+# Args: All arguments passed into script
+#+--------------------------------------------------------------------------+
+ {
+  : SOURCE: ${BASH_SOURCE}
+  : STACK:  ${FUNCNAME[@]}
+
+  while [ -n "$1" ]                        # loop through args passed in
+  do
+    case "$1" in
+      -h|--help)
+        usage
+        ;;
+      -v|--verbose) 
+        verbose=2
+        ;;
+      -x|--debug)                          # turn trace on
+         set -vx
+         ;;
+      *)
+	echo "ERROR: Too many arguments: $1"
+	usage 
+        ;;
+    esac
+    shift
+  done
+ }                                         # parseArgs()
+
+#+--------------------------------------------------------------------------+
+function doTest()
+# test recording with default microphone
+#+--------------------------------------------------------------------------+
+ {
+  : SOURCE: ${BASH_SOURCE}
+  : STACK:  ${FUNCNAME[@]}
+
+  # get microphone's sample rate, # of channels and format
+  rate=`grep rate: /proc/asound/card*/pcm0c/sub0/hw_params | awk '{print $2}'` # there could be multiple mic's
+  if [ "$verbose" = 2 ]; then
+    echo "rate = $rate"
+  fi    
+  if [ ${#rate} = 0 ]; then                # no mic found
+    echo "ERROR: no microphone found with command grep rate: /proc/asound/card*/pcm0c/sub0/hw_params"
+    exit 4                                 # cannot perform operation
+  fi
+  channels=`grep channels: /proc/asound/card*/pcm0c/sub0/hw_params | awk '{print $2}'`
+  if [ "$verbose" = 2 ]; then
+    echo "channels = $channels"
+  fi    
+  if [ ${#channels} = 0 ]; then            # number of channels not found
+    echo "WARNING: did not find number of channels - assuming 1"
+    channels=1                             # assume 1 channel
+  fi
+  format=`grep ^format: /proc/asound/card*/pcm0c/sub0/hw_params | awk '{print $2}'`
+  if [ "$verbose" = 2 ]; then
+    echo "format = $format"
+  fi    
+  if [ ${#format} = 0 ]; then              # format not found
+    echo "WARNING: did not find format - ignoring" # leave empty
+  else
+    format="-f $format"                    # add -f flag
+  fi
+  
+  # put the arecord command together and run it
+  cmd="arecord $format -c $channels -d 5 -r $rate /tmp/test-mic.wav"
+  echo "Testing your microphone for 5 seconds - SAY SOMETHING!"
+  echo "INFO: running command: $cmd"
+  $cmd                                     # run the command
+  rc=$?
+  if [ "$rc" != 0 ]; then                  # something didn't work
+    echo "ERROR: command $cmd failed with $rc"
+    exit $rc                               # not successful
+  fi
+ }                                         # doTest()
+
+#+--------------------------------------------------------------------------+
+# Global variables"
+verbose=1                                  # verbosity
+
+# main()
+parseArgs $@                                # parse arguments
+doTest                                      # perform the test 
+
