test for log dir not created

diff --git a/usr/local/sbin/tmpfsmnt b/usr/local/sbin/tmpfsmnt
--- a/usr/local/sbin/tmpfsmnt
+++ b/usr/local/sbin/tmpfsmnt
@@ -3,5 +3,17 @@
 # tmpfsmnt - mount tmpfs file systems over log file directories 
 #
 mount -t tmpfs -o size=100m,mode=1777 tmpfs /var/log
+
+# change user in logDir if it is not 'pi'
+logDir=/home/pi/.local/state/mycroft
+if [ ! -d $logDir ];
+  cmd="mkdir -p $logDir"
+  $cmd
+  rc=$?
+  if [ "$rc" != 0 ]; then
+    echo "ERROR: $cmd returned $rc"
+    exit 1
+  fi
+fi
 mount -t tmpfs -o size=100m,mode=1777 tmpfs /home/pi/.local/state/mycroft
 
